### ISSUE TITLE
[MECHANICS] Range z którego wrogowie się pulają

### ISSUE THREAD

**Issue by Makakahehe** [RaphaelSunwell/Sunwell-BugTracker#115]
**Opis**: Range ataku wrogów oraz evade jest trochę zbyt duży.

**Obecne działanie**: Wrogowie mają zbyt duży zasięg pulania się oraz mają niecny zwyczaj atakowania gracza w zbyt dużej ilośćci. Evade wydaje się być w porządku.

**Oczekiwane działanie**: Powinni mieć  zmniejszony zasięg z którego się pulają. Znalazłem filmik z globca w którym widać że nawet jak atakuje grupę mobów to pula się 2-3 a nie 5-10. Takich filmików jest więcej i w miarę możliwości poszukam je. Cał kanał w sumie jest o questach taurenów na low lvlu na globcu.

https://www.youtube.com/watch?v=k5FFlrXGP98
https://www.youtube.com/watch?v=OB3kCMjD6mY&list=PLA8A12964E5858C74&index=7

Wiem że to mało materiałów ale chcę zarysować ogólny problem o którym się cały czas mówi w kręgach testerów. Niezwykle utrudnia testy, szczególnie niższych lvli a nie wiemy czy będzie coś z tym zrobione.

**Comment by NoobSunwell** [comment]
Dobrze by było, jakbyś wskazał moment w tym filmiku, a także nagrał w tym samym miejscu jak to wygląda u nas.

**Comment by turboszczur** [comment]
Pierwszy filmik 3:50
Zrobiłem huntera 15 poziom mój i peta żeby spróbować odtworzyć sytuację z filmika.
Oto efekt: https://www.youtube.com/watch?v=AMyYs-wrTYE&feature=youtu.be

Jak widać pet spulał cały camp i tak się dzieje w prawie każdym low lvlowym queście. Na wyższych lvlach (60+) wydaje się być trochę lepiej z tym range. Może to nie jest kwestia range tylko tego że mobki się pulają wzajem, nie wiem.

**Comment by NoobSunwell** [comment]
Zasięg asysty u NPC wynosi 10yardów. Patrząc na filmiku to się zgadza. Najpierw Twój target woła o asystę, potem ten asystujący NPC znowu szuka, temu ten pull taki duży wyszedł.

**Comment by turboszczur** [comment]
Czyli takie chain pulle to jest coś normalnego ? Bo patrzę na ten 1szy filmik i jemu się nie pula wszystko naraz tylko na raty.  Tam za namiotem 1 npc strzela do peta ale nie pulnął tych obok siebie, jakbyś mógł zerknąć. Mogę się mylić lecz z tego co wygląda to ten npc co strzela jest definitywnie w zasięgu ale nie pulnał od razu tych 2 z tyłu dopiero pod koniec walki. Chodzi o to że ten npc który został zaatakowany przez peta jako 1 pulnął mu 2 obok a te który były dalej nie zostały pulnięte przez npce z assysty. U nas jest chain pull, każdy może pulać tych w zasięgu, tak to przynajmniej wygląda (chyba zaś zagmatwałem sprawę).

**Comment by turboszczur** [comment]
Czy npc nie powinien użyć asysty dopiero jak zostanie zaatakowany ? W sensie bezpośrednio, nie jak sam atakuje z asysty a jeszcze nikt go nie zaatakował.

**Comment by NoobSunwell** [comment]
No właśnie tego nie jestem pewien.

**Comment by turboszczur** [comment]
To co mam poszukać innego filmu z globca (z WotLK) i zrobić kolejne porównanie co byśmy byli pewni ?

**Comment by NoobSunwell** [comment]
Dobrze by było :)
