### ISSUE TITLE
[MOB] Brak akcji po użyciu Counterspell

### ISSUE THREAD

**Issue by ThePuppetMaster** [RaphaelSunwell/Sunwell-BugTracker#215]
**Opis**:
Spell: 65790
Przykładowy Mob: 18121
Problem dotyczy większości mobów casterów.

**Obecne działanie**:
Po przerwaniu mobowi casta pozostając poza melee rangem mob nie wykonuje akcji przez 8 sekund, jeżeli nie posiada spella z innej szkoły. (Watro przetestować działanie po dodaniu talentów w counterspell)

**Oczekiwane działanie**:
Mob powinien biec do gracza i bić go z melee.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Zaatakować moba castera, pozostając poza melee rangem.
2. Poczekać, aż zacznie castować
3. Przerwać mu cast za pomocą counterspell

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/npc=18121/angorosh-souleater
2. http://wotlk.openwow.com/spell=65790

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://postimg.org/image/6zvvbzmrn/

**Comment by NoobSunwell** [comment]
Dodałem do AI casterów, że jak mają silence to będą biegły do targetu wykonywać meele. Potrzebuję informacji odnośnie interruptu czasowego - jak to wygląda na globie? Nie sprawdzę, bo jeszcze przez 5 dni mam bana :/

**Comment by ThePuppetMaster** [comment]
Też tu nie pomogę. Zakładam, że skoro nietalentowany counterspell wyłącza daną szkołę na 8s, to po 8s powinien spokojnie zacząć castować (tak jak jest teraz).

**Comment by ThePuppetMaster** [comment]
Obecnie działa prawidłowo.
