### ISSUE TITLE
[ITEM/SPELL] Saronite Ore/Prospecting

### ISSUE THREAD

**Issue by nexx94** [RaphaelSunwell/Sunwell-BugTracker#307]
**Opis**: Nie jestem pewien czy zbugowany jest item czy spell

**Obecne działanie**: Prospecting saronite ore może dać dwa razy takie same kamienie, jak na screenie, zdarzało się z różnymi kolorami, przy innych ore nie zauważyłem (mała próbka)

**Oczekiwane działanie**: Kamienie powinny być różnych kolorów

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Prospectować saronite ore
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/spell=31252/prospecting#comments
2. http://www.wowhead.com/item=36912/saronite-ore#comments
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
Nie dotyczy
https://imgur.com/a/SGqfy

**Comment by ThePuppetMaster** [comment]
Zasięgnąłem trochę języka na retailu, poszperałem też w necie. Przebiłem się przez dużą część komentarzy na wowheadzie. Nie ma dowodu, że jest to bug. Jeżeli znajdziesz konkretny komentarz, proszę umieść go tutaj.

**Comment by nexx94** [comment]
Przy zgłaszaniu buga sugerowałem się tabelą lootu która pokazuje że z saronite ore można otrzymać 1-2 bloodstone, na screenie widać że otrzymałem 3.

**Comment by ThePuppetMaster** [comment]
Otrzymałeś 2 + 1, a to jest różnica.
Losowanie odbyło się osobno dla pierwszego stacka i osobno dla 2. W pierwszym przypadku kamyk wylosowało ci bloodstone, w 2 przypadku znów odbyło się losowanie i znów wpadł ci bloodstone.
