### ISSUE TITLE
[NPC] Uciekający vendor - Halaa

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#337]
**Opis**: Uciekający vendor.
https://youtu.be/WN272m43Bbo
https://youtu.be/a6zkruc-60s
https://youtu.be/lUwQ_cDJ_qw
https://youtu.be/aKyk99KZUYo

**Obecne działanie**: Wszystkie NPC, u których gracz może sprzedać/kupić/oddać quest, najzwyczajniej w świecie - uciekają.
**Oczekiwane działanie**: NPC powinien stać w miejscu.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Porozmawiać z jakimkolwiek vendorem w Halaa.

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/npc=18816
2. http://wotlk.openwow.com/npc=18817
3. http://wotlk.openwow.com/npc=18821
4. http://wotlk.openwow.com/npc=21483
5. http://wotlk.openwow.com/npc=21484
6. http://wotlk.openwow.com/npc=21474

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
https://zapodaj.net/b66c4f364e694.jpg.html
https://zapodaj.net/7bc90513f82e2.jpg.html

**Comment by vadren** [comment]
Moim zdaniem to jest ok, na globalu też NPC tak potrafią uciec i zamknąć okno, jeśli się mylę - Noob popraw mnie.
