### ISSUE TITLE
[NPC] Rachelle Gothena  ID [15354]

### ISSUE THREAD

**Issue by Lamadwarf** [RaphaelSunwell/Sunwell-BugTracker#348]
**Opis**: NPC stoi w mailboxie , cieżko nakliknąć.

**Obecne działanie**: TU WPISZ NA CZYM POLEGA PROBLEM

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ

**Co należy zrobić, aby odtworzyć ten błąd**:
1. 
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/npc=15354/rachelle-gothena
2. http://imgur.com/a/SOJnQ
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

1655 . 4430 . 17

**Comment by Dootz** [comment]
done
