### ISSUE TITLE
[quest] the battle for the ebon hold

### ISSUE THREAD

**Issue by Makakahehe** [RaphaelSunwell/Sunwell-BugTracker#351]
**Opis**: Grubasy dosłownie wyrywają nas sobie nawzajem.

**Obecne działanie**: Npce się agrują i każdy nas przyciąga łancuchem.

**Oczekiwane działanie**: Nie powinny tak się agrować i tyle przyciągać.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wziąć i zrobić q.
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. https://www.youtube.com/watch?v=BEkG4rQ4VB0
2. http://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold
3. http://www.wowhead.com/npc=31098/terrifying-abomination
4. https://www.youtube.com/watch?v=mL3PFvwFe5g

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/mTOhh

**Comment by turboszczur** [comment]
Npce przełażą se między poziomami

http://imgur.com/a/1Hc6E

http://www.wowhead.com/npc=31096/scourge-necromancer
http://www.wowhead.com/npc=31095/valkyr-battle-maiden
http://www.wowhead.com/npc=31099/patchwerk
