### ISSUE TITLE
ITEM nie działa " USE "

### ISSUE THREAD

**Issue by Xanador** [RaphaelSunwell/Sunwell-BugTracker#354]
**Opis**: 
NIe działa "use"

**Obecne działanie**: 
Po założeniu i użyciu http://wotlk.openwow.com/item=12344 nic się nie dzieje.

**Oczekiwane działanie**: TU WPISZ JAK TO POWINNO WYGLĄDAĆ
Po założeniu i użyciu http://wotlk.openwow.com/item=12344, powinien się aktywować spell:  http://wotlk.openwow.com/spell=16349

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Założyć http://wotlk.openwow.com/item=12344 w slot pierścionków.
2. Spróbować użyć.
3. Nic się nie dzieje.

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/item=12344  ITEM który nie działa
2. http://wotlk.openwow.com/spell=16349 SPELL który powinien się odpalić po użyciu

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
# Nietrzeba

**Comment by ThePuppetMaster** [comment]
Item powinien być używalny tylko podczas walki z http://www.wowhead.com/npc=10429/warchief-rend-blackhand
