### ISSUE TITLE
[npc] Disidra Stormglory

### ISSUE THREAD

**Issue by Makakahehe** [RaphaelSunwell/Sunwell-BugTracker#362]
**Opis**: Zostałem bezczelnie zarżnięty w dalaranie poprzez npca -_-.

**Obecne działanie**: Npc mnie zaatakował i zabił.

**Oczekiwane działanie**: Powinna mnie ignorować i zająć się własnymi sprawami -_-.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Nie mam pojęcia.
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/npc=32718/disidra-stormglory#comments
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/LiLrL

**Comment by Valleige** [comment]
Do tego ten taki dziwaczny pet npc hordowego jest zabijalny

**Comment by turboszczur** [comment]
Może to wina ashbringera.

**Comment by ThePuppetMaster** [comment]
To zdejmij i zobacz.

**Comment by Makakahehe** [comment]
Ta to ashbringer, na 99%.
