### ISSUE TITLE
[Rogue] Hunger of Blood.

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker#372]
**Opis**: W porozumieniu z pozostalymi Łotrzykami doszlismy do wspolnego wniosku, iz glyph of hunger of blood albo nie dziala, albo dziala i mamy visual buffa. Glyph zwieksza nam dmg z 5% do 8% zadawanych  wszystkich obrazen, natomiast po uzycia spellu widzimy minutowy buff (czas ok) na 5%.
http://screenshooter.net/102844212/jiqltcf
http://screenshooter.net/102844212/yljxahd
http://screenshooter.net/102844212/ohyrcnb

**Obecne działanie**: Buff pokazuje 5% zamiast 8% (Visual) LUB glyph nie dziala jak nalezy i pokazuje daje nam 5% zamiast 8%.

**Oczekiwane działanie**: Buff powinien zarowno dawac jak i pokazywac 8% z zalozonym glyphem.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Zalozyc glyph of hunger of blood na klasie Rogue.
2. Spelnic wymogi casta (aktywny bleed na celu) po czym uzyc ability.
3. Sprawdzic Buff.

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/item=45761
2. http://www.wowhead.com/spell=60177/hunger-for-blood
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
nie dotyczy.

**Comment by nexx94** [comment]
To nie jest visual, tooltipy spelli nigdy nie są aktualizowane przy talentach/glyphach które zmieniają ich wartości.
