### ISSUE TITLE
[Quest] Divination: Gorefiends Cloak - brak NPC

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#376]
**Opis**: Quest naprawiony. Mamy możliwość wykonania questa. Jednak teraz problemem jest brak NPC u którego gracz bierze/oddaje quest.
http://imgur.com/dQbI6DK

**Obecne działanie**: Brak NPC u ktorego gracz ma oddać quest.

**Oczekiwane działanie**: https://youtu.be/Ave3WSLTJLk?t=2m5s

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Odnaleźć NPC.
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/npc=21797
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/iaOSpzw

**Comment by Kougraa** [comment]
https://github.com/NoobSunwell/Sunwell-BugTracker/issues/267

**Comment by Bainit123** [comment]
Ja zepsułem tego NPC robiąc quest Teron Gorefiend I Am.
