### ISSUE TITLE
QUEST: Elven Legends ( instance )

### ISSUE THREAD

**Issue by Xanador** [RaphaelSunwell/Sunwell-BugTracker#379]
**Opis**: :::

**Obecne działanie**: 
Po znalezieniu odpowiedniego " NPC " i kliknieciu odpowiednich opcji, nie zalicza nam questa.

**Oczekiwane działanie**:
Po wzięciu **http://wotlk.openwow.com/quest=7481** wejściu do Dire Maul i odnalezieniu **http://wotlk.openwow.com/object=179544** i " rozmowie " powinno nam zaliczyć quest. Dodatkowo, po wybarniu opcji rozmowy ze szkieletem, Ten npc **http://wotlk.openwow.com/npc=14368** powinien się do nas odwrócić i powiedzieć:
I very much doubt that he will have anything to say, stranger...

I personally didn't mind him. It was the Prince who took exception to a high elf in his domain. Alas, I am not one to question the Prince. In his defense, he did not incinerate Master Winthalus immediately.

We most definitely do not need any more attention drawn to us, stranger. Return to those that sent you in search of the lost master and tell them that nothing could be found. When this is done - and I will know when it is so - return and I shall reveal the secrets of the deceased.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wziąć: http://wotlk.openwow.com/quest=7481
2. Porozmawiać ze szkieletem: http://wotlk.openwow.com/object=179544
3. Nie zalicza zadania.

**Linki WoWHead/OpenWoW**:
1. QUEST: http://wotlk.openwow.com/quest=7481
2. OBJECT DO POROZMAWIANIA: http://wotlk.openwow.com/object=179544
3. NPC KTÓRY MÓWI DO NAS COŚ O SZKIELECIE:http://wotlk.openwow.com/npc=14368

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/a/GLVBr

**Comment by Dootz** [comment]
done
