### ISSUE TITLE
[Instancja] The Oculus. - Mage-Lord Urom.

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker#403]
**Opis**: http://screenshooter.net/102844212/dmctjtb
Urom zamiast teleportowac sie i w swoim miejscu zostawic przyzywane moby, to teleportuje sie na nastepna platforme i tam dopiero zostawia moby. Robi tak z peirwszej na druga i z drugiej na trzecia platforme, gdyz z trzeciej na srodek juz przechodzi w stan "castu" w strone zrodla. Wedlug mojej grupy, to samo przytrafilo im sie na tej instancji w wersji normal.

**Obecne działanie**: Moby pojawiaja sie po teleporcie bossa.

**Oczekiwane działanie**: Boss powinien zostawiac moby w miejscu z ktorego ucieka, nie zabierac je ich ze soba.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Rozpoczac encounter w The Oculus z bossem Mage-Lord'em Urom'em.
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/npc=27655/mage-lord-urom
2. (3 typy mobow - 3 summony) http://www.wowhead.com/spell=50495/summon-menagerie
3. http://www.wowhead.com/spell=50476/summon-menagerie
   4.http://www.wowhead.com/spell=50496/summon-menagerie

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
The Oculus. (osobiscie robilem HC, ale grupa mowi rowniez o tym problemie w wersji normal)

**Comment by Shon-su** [comment]
done
