### ISSUE TITLE
[QUEST] - New Recruit

### ISSUE THREAD

**Issue by Bronchosol** [RaphaelSunwell/Sunwell-BugTracker#419]
*_Quest polegający na "obezwładnieniu" mobka i zaprowadzeniu go w wyznaczone miejsce. *_:

**Obecne działanie**: Bierzemy ze sobą mobka Lithe Stalker za pomocą przedmiotu  Sigil of the Ebon Blade, zgodnie z opisem w górę. Mobek znika a quest nie zostaje zaliczony.

**Oczekiwane działanie**: Po zabraniu mobka i odprowadzeniu go quest powinien zostać zaliczony. Zamieszczam 2 linki do YT jak to powinno w praktyce wyglądać.
https://www.youtube.com/watch?v=gHXFsFjcxRQ
https://www.youtube.com/watch?v=EGoA0Zu4glM

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Udać się do http://imgur.com/OeYqlRm i wziąć q
2. Podlecieć trochę wyżej wziąć ze sobą mobka wykorzystując do tego Sigil of the Ebon Blade
3. Odprowadzić go kawałek w stronę wyzej położonych skał.

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/quest=13143/new-recruit
2. http://wotlk.openwow.com/quest=13143

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/EPfWIRZ

**Comment by Kougraa** [comment]
#466 
Dodaje od siebie, iż NPC podąża ciągle za graczem.

**Comment by Shon-su** [comment]
done
