### ISSUE TITLE
[NPC] K3 Snow Runner - żyje czy nie żyje?

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#435]
**Opis**: NPC oszust. 
https://youtu.be/H407G7PMwoA

**Obecne działanie**: NPC mimo, iż chodzi - nie żyje. :laughing: 

**Oczekiwane działanie**: NPC powinien mieć HP.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Odnaleźć K3 Snow Runner.

**Linki WoWHead/OpenWoW**:
1. [NPC] http://www.wowhead.com/npc=29546/k3-snow-runner

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/6DkOqBN

**Comment by Shon-su** [comment]
done
