### ISSUE TITLE
[NPC] Snowblind Follower's i Garm Invader's.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#436]
**Opis**: Leniwe NPC.
http://i.imgur.com/qO8SFVq.jpg

**Obecne działanie**: NPC stoją w miejscu.
 https://youtu.be/ptIKeBWhrZg

**Oczekiwane działanie**: NPC powinny biegać.
https://youtu.be/JV7gJWk1z8k
https://youtu.be/Q2cJLbVYCew

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Odnaleźć NPC w Storm Peaks.

**Linki WoWHead/OpenWoW**:
1. [NPC] http://www.wowhead.com/npc=29619/garm-invader
2. [NPC] http://www.wowhead.com/npc=29618/snowblind-follower

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/IdIVAqR

**Comment by Nuy** [comment]
Zgłosiłem już to.

**Comment by Kougraa** [comment]
#397
