### ISSUE TITLE
[Mob] Nerubian Cocoon

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker#454]
**Opis**: https://youtu.be/1cUiJSshj1g kokon pullniety przy pomocy Arcane Torrent (racial belfki)

**Obecne działanie**: Pulniete kokony przybiegaja do nas.

**Oczekiwane działanie**: Pullniety kokon powinien miec roota, dawac nam tylko combat, stojac na miejscu.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Uzyc skilla nie powodujacego dmg w obszarze siegajacym kokon.
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/npc=28413/nerubian-cocoon
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/103007884/wtotwpg

**Comment by Shon-su** [comment]
done
