### ISSUE TITLE
[Quest] The Hunter and The Prince.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#472]
**Obecne działanie**: Brak objektu Bloodstained Stone. 
Albo jest tak mały i w ogóle niewidoczny dla gracza, albo go po prostu nie ma. 

**Oczekiwane działanie**: Objekt powinien być widoczny.
https://youtu.be/IHSFU-1rnto?t=33s

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wziąć quest od NPC.
2. Próbować odnaleźć objekt.

**Linki WoWHead/OpenWoW**:
1. [Quest] http://www.wowhead.com/quest=13400/the-hunter-and-the-prince
2. [Objekt] http://wotlk.openwow.com/object=194024
3. [NPC] http://wotlk.openwow.com/npc=32404

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/SmwaXMk

**Comment by nexx94** [comment]
Ja zrobiłem quest bez problemu, rozejrzyj się za kamieniem jeszcze raz.

**Comment by Kougraa** [comment]
@nexx94  w takim razie zaloguj i pokaż. Bo wydaje mi się, że go jednak nie ma ;)

**Comment by Kougraa** [comment]
Ok, więc.. Kilkukrotnie próbowałam wyrzucić quest i za którymś razem pojawił się kamień (dość spory), wcześniej go nie było. 
Jeśli gracz nie ubije za pierwszym razem Illidana - przy kolejnej próbie podejśca do questa, gracz musi stoczyć walkę z jednym wiecej Illidanem... [ Tak się nazbierało nawet 3 :laughing: ].
1. [NPC] http://www.wowhead.com/npc=22917/illidan-stormrage
2. https://youtu.be/KqiDNiVUpW4

**Comment by ThePuppetMaster** [comment]
Osobne zgłoszenie.
