### ISSUE TITLE
[quest] the bones of nozronn

### ISSUE THREAD

**Issue by Makakahehe** [RaphaelSunwell/Sunwell-BugTracker#475]
**Opis**: Prawie autocomplete.

**Obecne działanie**: Po użyciu q itema nic się nie dzieje a po chwili q nam zalicza.

**Oczekiwane działanie**: Powinno się trochę poświecić i kości powinny do nas przemówić (takie szamańskie voodoo).

Voice of Nozronn says: So the oracIe has decided to aid you, outIander. Very weII, l will offer you what i know.
Voice of Nozronn says: Your companion seeks the shardhorn patriarch Farunn, who holds himself aIoof from his brothers.
Voice of Nozronn says: Farunn walks the lands north of what your people call the Bittertide Falls. You will find him alone, but you will see her requires no defenders.
Voice of Nozronn says: Return to your companion. TelI him to go forth and claim his prize in Farunn.
Voice of Nozronn says: Once he has done so, tell him to Ieave this land in peace. He does not belong here.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wziąć i zrobić q.
2. 
3. 

**Linki WoWHead/OpenWoW**:
1. http://www.wowhead.com/quest=12544/the-bones-of-nozronn
2. https://www.youtube.com/watch?v=Cp5bzmMqsio
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

http://imgur.com/a/VT9ld

**Comment by Shon-su** [comment]
done
