### ISSUE TITLE
Quest [Redridge Goulash]

### ISSUE THREAD

**Issue by Lilianka88** [RaphaelSunwell/Sunwell-BugTracker#478]
**Opis**: Quest polegający na zabiciu 3 rodzajów mobów, w celu wydropienia składników do gulasz.

**Obecne działanie**: Bug dość mało istotny ale jednak jest. Problem jest w tym, że nie pokazuje na tooltipie q dropu z mobów, z których faktycznie lecą q itemy. Dla porównania (żeby nie czepiać się do mojego UI) zrobiłam screena w tym samym miejscu, "najeżdzając na innego mobka z innego q i tam wszystko działa jak należy.

**Oczekiwane działanie**: Po najechaniu kursorem myszki na moby, które dropią q itemy, powinna być informacja w tooltipie o istniejącym dropie.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Udać się do Redrige Mountains.
2. Wziąć quest [Redrige Goulash] od Chef Breanna.
3. Odnaleźć mobki potrzebne do q i "najeżdzać" na nie myszką.

**Linki WoWHead/OpenWoW**:
1. http://wotlk.openwow.com/npc=343 - Chef Breanna
2. http://wotlk.openwow.com/quest=92 - opis questu
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/VxCVJJw.jpg
http://i.imgur.com/Rbo0Mli.jpg

**Comment by ThePuppetMaster** [comment]
Żeby udowodnić, że bug nie jest związany z UI wyłącz wszystkie addony.

**Comment by Lilianka88** [comment]
By udowodnić, że to nie wina addonu, wskazałam inne mobki, które działały prawidłowo. Polecam opcję "Co należy zrobić, aby odtworzyć ten błąd:" by samemu się przekonać. W końcu po coś to zostało stworzone, prawda?
