### ISSUE TITLE
[NPC] Void Summoner.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#481]
**Opis**: Void i jego pet.

**Obecne działanie**: Pet Summonera nie znika w chwili zabicia NPC. 
https://youtu.be/v1W1DCXrUzs

**Oczekiwane działanie**: Pet po zabiciu Voida powinien zniknąć.

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Odnaleźć Voida Summonera.
2. Zabić NPC.

**Linki WoWHead/OpenWoW**:
1. [NPC] http://www.wowhead.com/npc=32259/void-summoner
2. [Pet] http://www.wowhead.com/npc=32260/enslaved-minion

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/RvB53k6

**Comment by nexx94** [comment]
Z komentarzy pod tym questem wynika że tak ma być:
http://www.wowhead.com/quest=13342/not-a-bug#comments
https://youtu.be/F_c2skBctog?t=3m22s
Na filmiku z globa z innego patcha pet również nie znika.
Moim zdaniem działa jak powinno

**Comment by Kougraa** [comment]
Z komentarzy pod questem można wywnioskować, że NPC: Wracking Prisoners (konkretnie 3 npc http://imgur.com/rgXNg3s) nie powinny stać, powinny leżeć. Udało mi się zrobić ss z filmu poświęconemu wlaśnie temu questowi- https://youtu.be/FNZIgbFXoOw?t=1m53s , http://imgur.com/cBoJA25 .

[NPC] http://www.wowhead.com/npc=32275/wracked-prisoner#comments

**Comment by ThePuppetMaster** [comment]
Do mobów, które stoją, przydało by się osobne zgłoszenie.
