### ISSUE TITLE
[Quest] Neutralizing the Plague.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#484]
**Obecne działanie**: Quest item pomimo długiego czasu poszukiwań - nie chce wypaść. 

**Oczekiwane działanie**: Qitem przy 7% dropie powinien wypadać częściej. 

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Wziąć quest.
2. Odnaleźć i zabić NPC z którego dropi item.

**Linki WoWHead/OpenWoW**:
1. [Qitem] http://www.wowhead.com/item=44009/flesh-giant-spine
2. [Quest] http://www.wowhead.com/quest=13297/neutralizing-the-plague
3. [NPC] http://www.wowhead.com/npc=31139/pustulent-horror
4. http://www.wowhead.com/npc=32482/pustulent-colossus

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/NdUFCWf

-> Itemy mające po 0.1% dropu wypadają częściej.

**Comment by Shon-su** [comment]
done
