### ISSUE TITLE
[NPC] Onslaught Raven Priest (visual).

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#510]
**Opis**: NPC powinien być w shadowformie.

**Obecne działanie**: NPC nie jest w shadowformie.
https://youtu.be/pR2tb7gwlz0

**Oczekiwane działanie**: NPC powinien być w shadowformie.
https://youtu.be/aSWZaQspKhA

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=27202/onslaught-raven-priest

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/KHFxvEH

**Comment by Riztazz** [comment]
`sql
DELETE FROM `creature_template_addon` WHERE `entry` = 27202;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(27202, 0, 0, 0, 1, 0, '48154');
`

**Comment by Riztazz** [comment]
```sql
DELETE FROM `creature_template_addon` WHERE `entry` = 27202;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(27202, 0, 0, 0, 1, 0, '48154');
```

**Comment by Shon-su** [comment]
blisko ale nie tutaj był błąd :D
