### ISSUE TITLE
[Quest] Defending Wyrmrest Temple.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#524]
**Opis**: Trzeba się nieźle natrudzić, żeby wsiąść na smoka ;d.
https://youtu.be/2PMBi4muPz8

**Obecne działanie**: Smok jest zbyt wysoko.

**Oczekiwane działanie**: Smok powinien być niżej.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Próbować wsiąść na smoka.

**Linki WoWHead/OpenWoW**:

1. [Quest] http://www.wowhead.com/quest=12372/defending-wyrmrest-temple 
2. [Smok] http://www.wowhead.com/npc=27629/wyrmrest-defender

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/Ksmey6X

**Comment by Shon-su** [comment]
done
