### ISSUE TITLE
[Naxxramas] Noth the Plaguebringer.

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker#534]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: https://youtu.be/OifZhJAtOp0?t=37m7s

**Obecne działanie**: Po przejsciu w druga faze (Balcony phase) Noth zbiega spowrotem na dol i tam przeczekuje cala faze. (visual)

**Oczekiwane działanie**: Noth powinien przezcala faze grzecznie stac na balkonie.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejsc do naxxa, plague quarter.
2. Rozpoczac walke z Nothem.
3. Poczekac do drugiej fazy.

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=15954/noth-the-plaguebringer
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/103008095/kkjmvke

**Comment by Shon-su** [comment]
zrobione
