### ISSUE TITLE
[Naxxramas] Gothik the Harvester.

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker#542]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: https://youtu.be/K1FLiyBfAug?t=22m30s
Wszystkie mobki wymienione w "article" w linku podanym ponizej nie uzywaja swoich spelli. Boss dziala normalnie.

**Obecne działanie**: Addy na bossie nie uzywaja swoich umiejetnosci.

**Oczekiwane działanie**: Addy powinny uzywac swoich unikalnych zdolnosci.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wejsc do naxxa, rozpoczac encounter z Gothikiem
2. Poczekac az zrespia sie moby i zaobserowowac ich pasywnosc.
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=16060/gothik-the-harvester#article
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/103008095/iljpddg (gps naxxa, brak mozliwosci dojscia do Gothika na nowym id raidu)

**Comment by Makakahehe** [comment]
Tu jest filmik z WotLK jak to wyglądało https://www.youtube.com/watch?v=zZmyQlQdAnA

**Comment by Shon-su** [comment]
done
