### ISSUE TITLE
<npc> Brassbolt Mechawrench

### ISSUE THREAD

**Issue by valcy** [RaphaelSunwell/Sunwell-BugTracker#547]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Ukochany Auctioneer w dalaranie.

**Obecne działanie**: Brak npc.
**Oczekiwane działanie**: Kolo trainerow engi powinien stac nasz NPC umozliwiajacy grand master engineerom korzystania z uslug Auction House.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wlaczyc gre.
2. Wyskillowac engi.
3. Zalamac sie brakiem NPC.

**Linki WoWHead/OpenWoW**:

1. http://i.imgur.com/2MNF5u2.jpg
2. http://wowwiki.wikia.com/wiki/Brassbolt_Mechawrench
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:

**Comment by nexx94** [comment]
Dodany w patchu 3.2.0., prawdopodobnie usunięty celowo.

**Comment by RaphaelSunwell** [comment]
dodano dopiero w patchu 3.2.0
