### ISSUE TITLE
[Naxxramas] Dialog LK-KT przy wejsciu do sali Kelthuzada.

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker#565]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: https://youtu.be/_pBIW0We5dU?t=2m59s - 10man, (w miare) czysty dzwiek.
https://youtu.be/2qUOUyYm47E?t=1h37m51s - 25man, z raidu.

Caly problem zostal zauwazony na 25manie, ale bardziej ktos spostrzegl, ze LK uzywa innego voica, anizeli tekstu. Ja zauwazylem roznice w tekscie bo braklo mi charakterystycznego "Naxxramas must not fall!". Slowa, ktore wypowiada LK na naszym serverze roznia sie od slow wypowiadanych przez LK na innych wotlkach. Podejrzewam, aczkolwiek nie mam pewnosci, ze sa to slowa z vanilli. Niestety wszystkie filmiki pochodza z samego encounteru i nie zawieraja tej wymiany zdan. Poszperalem troche w necie i udalo mi sie znalezc tekst wotlkowy:

KT: Your forces are nearly marshalled to strike back against your enemies, my liege.
LK: Soon we will eradicate the Alliance and Horde, then the rest of Azeroth will fall before the might of my army.
KT: Yes, Master. The time of their ultimate demise grows close... What is this?
LK: Invaders...here? DESTROY them, Kel'Thuzad! Naxxramas must not fall!
KT: As you command, Master!

Natomiast u nas mozna zaobserowac tekst ktory brzmi:

KT: Your forces are nearly marshalled to strike back against your enemies, my liege.
LK: It is good that you serve me so faithfully. Soon, all will server the Lich King and in the end you shall be rewarded... so long as you do not falter.
KT: Yes, Master. The time of their ultimate demise grows close... What is this?
LK: Your security measures have failed! See to this interruption immediately!
KT: As you command, Master!

Tak jak napisalem wyzej, rowniez glos nie brzmi jak ten spod Ahn'rethar'u, z areny w Trial of the Crusader, w Utgarde PInnacle, czy w calym ICC. Ten jest taki... gejowski. Ladnie mowiac - starszy "technicznie", stad moje podejrzenia, ze to glos z vanilli.

**Obecne działanie**: Zla sciezka dzwiekowa i tekst na czacie u Lich Kinga.

**Oczekiwane działanie**: wyzej podana opcja 

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Przejsc przez framuge drzwi prowadzaca do sali Kelthuzada w Naxxramas.
2. 
3. 

**Linki WoWHead/OpenWoW**:

1. http://www.wowhead.com/npc=15990/kelthuzad
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/103008095/tusoygt (niestety bylem nagrac filmik, ale oczywiscie o gpsie zapomnialem...)

**Comment by Mithras2801** [comment]
Rozmowa powinna się zacząć kilka sekund po zabiciu smoka. W momencie podejścia do bramy powinien kończyć się dialog.

**Comment by Shon-su** [comment]
poprawione
