### ISSUE TITLE
[NPC] Wracked Prisoners.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#567]
**Opis**: 
http://i.imgur.com/cBoJA25.jpg
http://www.wowhead.com/quest=13342/not-a-bug#screenshots:id=181721
https://www.youtube.com/watch?v=FNZIgbFXoOw&feature=youtu.be&t=1m53s

**Obecne działanie**: NPC stoją.

**Oczekiwane działanie**: NPC powinny leżeć.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC.. 

**Linki WoWHead/OpenWoW**:

1. [NPC] http://www.wowhead.com/npc=32275/wracked-prisoner

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://i.imgur.com/rgXNg3s.jpg

**Comment by Shon-su** [comment]
zrobione
