### ISSUE TITLE
[NPC] problem z lataniem

### ISSUE THREAD

**Issue by nirvaaa** [RaphaelSunwell/Sunwell-BugTracker#568]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Problem latającego npc.

**Obecne działanie**: Npc podpływa i atakuje.

**Oczekiwane działanie**: Npc powinien atakować na mount`cie.

**Co należy zrobić, aby odtworzyć ten błąd**: zaagrować podanego npc

1. http://wotlk.openwow.com/npc=29332
Sprawdzalem parę innych latających npc i nie było u nich problemów.
2. <a href='https://postimg.org/image/4j0c3h4xj/' target='_blank'><img src='https://s15.postimg.org/58j4fu5h7/Wo_WScrn_Shot_110716_105634.jpg' border='0' alt='WoWScrnShot_110716_105634'/><br /><a target='_blank' href='https://postimage.org/app.php'>greenshot</a><br /><br />

**Comment by kovaq** [comment]
#467
