### ISSUE TITLE
Bug z wyświetlaniem Expa

### ISSUE THREAD

**Issue by nirvaaa** [RaphaelSunwell/Sunwell-BugTracker#571]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Niewłaściwe wyświetlanie expa.

**Obecne działanie**: W jednym z etapów robienia q exp jest zaniżany o połowę.

**Oczekiwane działanie**: W każdym etapie robienia q exp powinien być wyświetlany taki sam.

**Co należy zrobić, aby odtworzyć ten błąd**: 

1. Exp się zgadza 
<a href='https://postimg.org/image/umezcgrhd/' target='_blank'><img src='https://s16.postimg.org/umezcgrhd/Wo_WScrn_Shot_110816_162404.jpg' border='0' alt='postimage'/></a>
2. Exp jest obniżony do 1/2
<a href='https://postimg.org/image/t6dxep37v/' target='_blank'><img src='https://s17.postimg.org/t6dxep37v/Wo_WScrn_Shot_110816_162413.jpg' border='0' alt='postimage'/></a>
3. Exp się zgadza
<a href='https://postimg.org/image/wivnz4fhl/' target='_blank'><img src='https://s4.postimg.org/wivnz4fhl/Wo_WScrn_Shot_110816_164034.jpg' border='0' alt='postimage'/></a>
4. Exp się zgadza
<a href='https://postimg.org/image/glt7enzkv/' target='_blank'><img src='https://s11.postimg.org/glt7enzkv/Wo_WScrn_Shot_110816_164038.jpg' border='0' alt='postimage'/></a>

Działo się tak ze wszystkimi q, które robiłem do 15 lvlu począwszy od startowego.
Oczywiście addony wyłączone.

**Comment by RaphaelSunwell** [comment]
Exp został zwiększony chwilowo na x2 dlatego ten błąd tak wygląda.
