### ISSUE TITLE
[Quest] The Hunter and The Prince.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#575]
**Opis**: Jeśli gracz nie ubije za pierwszym razem Illidana - przy kolejnej próbie podejśca do questa, gracz musi stoczyć walkę z jednym wiecej Illidanem... [ Tak się nazbierało nawet 3 :laughing: ].
https://youtu.be/KqiDNiVUpW4

**Obecne działanie**: Po nieukończeniu questa i ponowej próbie jego wykonania - Illidanów jest dwóch. Z każdą kolejną próbą podejścia do questa jest +1 NPC.

**Oczekiwane działanie**: W chwili, gdy gracz nie ukończy questa zabijając Illidana, przy każdym kolejnym podejściu do questa - powinien pojawić się 1 NPC.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest i kliknac objekt ppm.
2. Pozwolić zabić się Illidanowi.
3. Wyrzucić quest i wziąć go ponownie.
4. Kliknąć kolejny raz kamień.

**Linki WoWHead/OpenWoW**:

1. [NPC] http://www.wowhead.com/npc=22917/illidan-stormrage
2. [Quest] http://www.wowhead.com/quest=13400/the-hunter-and-the-prince
3. [Objekt] http://wotlk.openwow.com/object=194024

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/SmwaXMk

**Comment by Shon-su** [comment]
done
