### ISSUE TITLE
[Mapa] Instant odkryta mapa

### ISSUE THREAD

**Issue by nirvaaa** [RaphaelSunwell/Sunwell-BugTracker#581]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Złe działanie mapy

**Obecne działanie**: Lokacje są w pełni odkryte mimo nie bycie w nich.

**Oczekiwane działanie**: Powinny być zakryte.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. <a href='https://postimg.org/image/pxc3dmfun/' target='_blank'><img src='https://s11.postimg.org/wb16gvkqr/Wo_WScrn_Shot_111016_123747.jpg' border='0' alt='WoWScrnShot_111016_123747'/><br /><a target='_blank' href='https://postimage.org/'>upload images free</a><br /><br />
2. <a href='https://postimg.org/image/u7g6v8wfl/' target='_blank'><img src='https://s16.postimg.org/i5kt13n79/Wo_WScrn_Shot_111016_123737.jpg' border='0' alt='WoWScrnShot_111016_123737'/><br /><a target='_blank' href='https://postimage.org/'>image hosting services</a><br /><br />

**Comment by Bainit123** [comment]
A nie masz jaiegoś addonu który odkywa ci całą mapę? Przebiegnij się i zobacz czy dostajesz expa za explore.

**Comment by ThePuppetMaster** [comment]
I wklej achi za explore.

**Comment by nirvaaa** [comment]
Racja, Zygor addon odkrył mi mapę.
Do usunięcia
