### ISSUE TITLE
[Quest] Ursoc, the Bear God.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#583]
#380  Tyle złego i jeszcze więcej :)
**Opis**: Gracz ma za zadanie zabić niedźwiedzia przy pomocy NPC. Przy czym gracz ma możliwość wyboru roli NPC (tank, heal, dps). Następnie użyć qitemu na nie żyjącym już niedźwiedziu.

**Obecne działanie**: W chwili dotarcia na miejsce - NPC znika, a gracz musi stoczyć walkę z misiem 1v1. 
Myśle, że jest to spowodowane przebiciem aggro.
https://youtu.be/RYQ71jrajVc

**Oczekiwane działanie**: NPC powinien pomagać graczowi zabić niedzwiedzia.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Wziąć quest.
2. Odnaleźć NPC i wybrać jego rolę. 
3. Podążać za NPC. 

**Linki WoWHead/OpenWoW**:

1. [Quest] http://wotlk.openwow.com/quest=12236
2. [Quest item] http://wotlk.openwow.com/item=37307
3. [NPC] http://wotlk.openwow.com/npc=27328
4. [Niedźwiedź] http://www.wowhead.com/npc=26633/ursoc

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://imgur.com/mpviGjB

**Comment by kovaq** [comment]
Ladniej opisane niz w #380 , ale to wciaz to samo :p

**Comment by Makakahehe** [comment]
Zamiast duplikować wrzuć to do komentarza, ułatwi to pracę devom.
