### ISSUE TITLE
[NPC] Shade of Arugal.

### ISSUE THREAD

**Issue by Kougraa** [RaphaelSunwell/Sunwell-BugTracker#594]
**Obecne działanie**: NPC ma 106k hp.
http://imgur.com/VA3l12O

**Oczekiwane działanie**: NPC powinien mieć 51,180hp.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Odnaleźć NPC.

**Linki WoWHead/OpenWoW**:

1. [NPC] http://www.wowhead.com/npc=27018/shade-of-arugal

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
GPS nie działa.

**Comment by Kokaina** [comment]
On ma 106k hp na wotlku, większość elitek ma tyle na north (npc. Gigantaur i inne w dragonblight). Te 51.180 zostało zmienione później.

**Comment by Kougraa** [comment]
HP pozostałych elit, należących do questa się zgadza.

**Comment by Kokaina** [comment]
https://www.youtube.com/watch?v=F8qsphRUR8M
4:10 Filmik z 2009 roku na globie, Arugal ma 106.3k hp
Catalysm wszedł w 2010 roku więc to jest wotlk.

**Comment by Rzuuf** [comment]
potwierdzam Koke

**Comment by Kougraa** [comment]
Faktycznie masz racje. Zamykam.
