### ISSUE TITLE
Quest Tomber's Supplies

### ISSUE THREAD

**Issue by Jarek250** [RaphaelSunwell/Sunwell-BugTracker#607]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**:Niedziałający quest Tomber's Supplies

**Obecne działanie**: Brak respienia sie objektu  Rathis Tomber's Supplies

**Oczekiwane działanie**: Naprawa respawnu Rathis Tomber's Supplies

**Co należy zrobić, aby odtworzyć ten błąd**:

1. 
2. 
3. 

**Linki WoWHead/OpenWoW**: http://www.wowhead.com/quest=9152/tombers-supplies

1. 
2. 
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**: 33,26 Ghostlands

**Comment by Shon-su** [comment]
z tego co widzę respi się co 15 minut
